kind: DaemonSet
apiVersion: apps/v1
metadata:
  # Replaced at runtime.
  name: router
  namespace: openshift-cluster-ingress-router
  labels:
    app: router
spec:
  # Replaced at runtime.
  selector:
    matchLabels:
      app: router
      router: router
  template:
    metadata:
      # Replaced at runtime.
      labels:
        app: router
        router: router
    spec:
      serviceAccountName: router
      nodeSelector:
        "node-role.kubernetes.io/infra": "true"
      containers:
        - name: router
          image: "docker.io/openshift/origin-haproxy-router:v3.11.0"
          imagePullPolicy: IfNotPresent
          ports:
          - name: http
            containerPort: 80
            protocol: TCP
          - name: https
            containerPort: 443
            protocol: TCP
          - name: stats
            containerPort: 1936
            protocol: TCP
          # Merged at runtime.
          env:
          - name: STATS_PORT
            value: "1936"
          - name: ROUTER_SERVICE_NAMESPACE
            value: openshift-cluster-ingress-router
          livenessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: /healthz
              port: 1936
          readinessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: /healthz
              port: 1936
