# Cluster Service with default values
# Cluster Ingress specific annotations are applied at runtime.
kind: Service
apiVersion: v1
metadata:
  # Name and Annotations are set at runtime.
  namespace: openshift-ingress
  labels:
    app: router
spec:
  type: ClusterIP
  selector:
    app: router
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  - name: https
    port: 443
    protocol: TCP
    targetPort: https
  - name: metrics
    port: 1936
    protocol: TCP
    targetPort: 1936
