# Cluster role for the operator itself.
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: cluster-ingress-operator
  namespace: openshift-cluster-ingress-operator
rules:
- apiGroups:
  - ingress.openshift.io
  resources:
  - clusteringresses
  verbs:
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - daemonsets
  verbs:
  - create
- apiGroups:
  - ""
  - rbac.authorization.k8s.io
  resources:
  - namespaces
  - pods
  - endpoints
  - services
  - serviceaccounts
  - configmaps
  - clusterroles
  - clusterrolebindings
  verbs:
  - create
  - list
  - watch
