# Binds the operator cluster role to its Service Account.
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: cluster-ingress-operator
subjects:
- kind: ServiceAccount
  name: cluster-ingress-operator
  namespace: openshift-cluster-ingress-operator
roleRef:
  kind: ClusterRole
  name: cluster-ingress-operator
  namespace: openshift-cluster-ingress-operator
userNames:
- "system:serviceaccount:openshift-cluster-ingress-operator:cluster-ingress-operator"
