# Binds the operator cluster role to its Service Account.
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-ingress-operator:operator
subjects:
- kind: ServiceAccount
  name: cluster-ingress-operator
  namespace: openshift-cluster-ingress-operator
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: cluster-ingress-operator:operator
