# IngressController with default values
# Installer config specific values are applied at runtime.
kind: IngressController
apiVersion: operator.openshift.io/v1
metadata:
  name: default
  namespace: openshift-ingress-operator
  finalizers:
  # Ensure that only the operator can delete the default cluster ingress object.
  finalizers:
  - ingress.openshift.io/ingress-controller
spec: {}
